import hashlib
import json
from datetime import datetime
from typing import List, Dict, Any, Optional
from core_ai.ai_engine import generate_auto_reasoning

class AgentBridgeMonitor:
    def __init__(self, previous_hash: str = "00000000000000000000000000000000"):
        self.previous_hash = previous_hash

    def calculate_log_hash(self, data: Dict[str, Any]) -> str:
        data_to_hash = {k: v for k, v in data.items() if k != "log_hash"}
        content = json.dumps(data_to_hash, sort_keys=True) + self.previous_hash
        return hashlib.sha256(content.encode()).hexdigest()

    def run_rbi_checks(self, log: Dict[str, Any]) -> List[Dict[str, Any]]:
        """
        AI Feature 6 — RBI Clause Checker (Rule Engine)
        Implements the exact check sequence for Clauses 1.3 to 6.1.
        """
        violations = []
        
        # 1. Clause 1.3: if not log.agent_name -> violation
        if not log.get("agent_id") and not log.get("agent_name"):
            violations.append({"clause": "1.3", "severity": "medium", "description": "Missing agent_name identification."})

        # 2. Clause 2.1: if not log.input or log.input == {} -> violation
        inputs = log.get("inputs", log.get("input", {}))
        if not inputs or inputs == {} or inputs == "{}":
            violations.append({"clause": "2.1", "severity": "medium", "description": "Missing or empty decision inputs."})

        # 3. Clause 3.1: if not log.reasoning or log.reasoning == "" -> trigger Groq auto-reasoning -> if still empty -> violation
        reasoning = log.get("reasoning", "")
        if not reasoning or reasoning.strip() == "":
            print("  → Triggering Groq Auto-Reasoning (Feature 1)...")
            generated = generate_auto_reasoning(
                log.get("agent_id", "unknown"),
                log.get("action_type", "unknown"),
                inputs,
                log.get("output", "")
            )
            if not generated or generated.strip() == "":
                violations.append({"clause": "3.1", "severity": "medium", "description": "Failure of decision interpretability (reasoning empty)."})
            else:
                log["reasoning"] = generated # Update reasoning in original log
                log["ai_explanation"] = "Auto-generated by AgentBridge for RBI 3.1 compliance."

        # 4. Clause 4.2: if not log.created_at -> auto-assign -> pass
        if not log.get("created_at"):
            log["created_at"] = datetime.utcnow().isoformat()
        
        # 5. Clause 4.4: if not log.session_id -> violation
        if not log.get("session_id"):
            violations.append({"clause": "4.4", "severity": "medium", "description": "Missing session_id for audit trail."})

        # 6. Clause 5.0: if not log.output or log.output == {} -> violation
        if not log.get("output"):
            violations.append({"clause": "5.0", "severity": "medium", "description": "Missing decision output."})

        # 7. Clause 5.2: if log.action_type not in approved list -> violation
        approved_actions = ["approve", "reject", "flag", "escalate", "query", "review"]
        if log.get("action_type") not in approved_actions:
            violations.append({"clause": "5.2", "severity": "medium", "description": f"Invalid action_type: {log.get('action_type')}"})

        # 8. Clause 6.1: if log.action_type == "approve" and log.input.kyc_verified != true -> violation
        if log.get("action_type") == "approve":
            kyc = False
            if isinstance(inputs, dict): kyc = inputs.get("kyc_verified")
            if kyc != True:
                violations.append({"clause": "6.1", "severity": "high", "description": "RBI Clause 6.1: Approval granted without KYC verification."})

        return violations

    def process_log(self, raw_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Main pipeline that processes an incoming agent decision logic.
        Matches Gateway v5 Supabase Schema.
        """
        # Mapping to internal Gateway v5 naming
        record = {
            "agent_id": raw_data.get("agent_id", raw_data.get("agent_name")),
            "action_type": raw_data.get("action_type"),
            "inputs": raw_data.get("inputs", raw_data.get("input")),
            "output": raw_data.get("output"),
            "reasoning": raw_data.get("reasoning"),
            "confidence": float(raw_data.get("confidence", 0.0)),
            "session_id": raw_data.get("session_id"),
            "user_id": raw_data.get("user_id"),
            "decision_id": raw_data.get("decision_id", raw_data.get("log_id", f"DEC-{datetime.utcnow().timestamp()}")),
            "created_at": raw_data.get("created_at"),
            "domain": raw_data.get("domain", "fintech"),
            "api_key": raw_data.get("api_key", "test123")
        }

        # Run RBI Check Sequence (Feature 6 & Feature 1 integration)
        violations = self.run_rbi_checks(record)

        # Risk scoring
        flagged = len(violations) > 0
        risk_level = "low"
        risk_score = 0.0
        if any(v["severity"] == "high" for v in violations):
            risk_level = "high"
            risk_score = 0.85
        elif violations:
            risk_level = "medium"
            risk_score = 0.45

        # Final record preparation
        record.update({
            "verdict": "reject" if risk_level == "high" else "review" if flagged else "allow",
            "risk_score": risk_score,
            "risk_level": risk_level,
            "flagged": flagged,
            "policy_violations": [],
            "compliance_violations": [v["description"] for v in violations],
            "compliance_tags": [v["clause"] for v in violations],
            "inputs": json.dumps(record["inputs"]) if isinstance(record["inputs"], (dict, list)) else str(record["inputs"]),
            "status": "processed",
            "ai_compliance_status": "fail" if flagged else "pass",
            "ai_risk_level": risk_level,
            "ai_issue_detected": flagged,
            "ai_regulatory_refs": [v["clause"] for v in violations],
            "previous_hash": self.previous_hash,
            "latency_ms": 15
        })

        # Cryptographic Hashing
        record["log_hash"] = self.calculate_log_hash(record)
        return record
