"""
routes/audit_routes.py
Audit-specific endpoints: chain verification, incidents, reports.
"""
from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse
from database import supabase
from app_logging.audit_logger import verify_chain
from core_ai.dao import DAO
from core_ai.report_generator import generate_report
from core_ai.report_cleaner import clean_report
import ast
import json
from datetime import datetime, timezone

router = APIRouter()


# ─────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────

def _parse(raw) -> dict:
    if isinstance(raw, dict):
        return raw
    try:
        return ast.literal_eval(str(raw))
    except Exception:
        return {}


def _build_daos(logs: list) -> list:
    """Shared logic: convert Supabase rows → DAO objects."""
    daos = []
    for l in logs:
        dao = DAO(
            decision_id=l.get("decision_id") or "",
            session_id=l.get("session_id") or "",
            timestamp=str(l.get("created_at", "")),
            agent_name=l.get("agent_id") or "",
            action_type=l.get("action_type") or "unknown",
            risk_level=l.get("risk_level") or "low",
            flag_reason=l.get("policy_violations", [None])[0] if l.get("policy_violations") else None,
            reasoning=l.get("reasoning"),
            compliance_tags=l.get("compliance_tags") or [],
            compliance_violations=l.get("compliance_violations") or [],
            input=_parse(l.get("inputs")),
            output=_parse(l.get("output")),
            ai_explanation=l.get("ai_explanation"),
            ai_recommended_action=l.get("ai_recommended_action"),
            ai_escalate_to_human=l.get("ai_escalate_to_human", False),
            ai_regulatory_refs=l.get("ai_regulatory_refs") or [],
            ai_compliance_status=l.get("ai_compliance_status"),
        )
        daos.append(dao)
    return daos


def _fetch_logs(api_key: str, session_id=None) -> list:
    query = supabase.table("audit_logs").select("*").eq("api_key", api_key)
    if session_id:
        query = query.eq("session_id", session_id)
    return query.order("created_at", desc=True).execute().data


# ─────────────────────────────────────────
# ROUTES
# ─────────────────────────────────────────

@router.get("/incidents")
async def get_incidents(api_key: str):
    result = supabase.table("audit_logs")\
        .select("*")\
        .eq("api_key", api_key)\
        .eq("flagged", True)\
        .order("created_at", desc=True)\
        .execute()
    return result.data


@router.get("/report")
async def get_report(api_key: str, session_id: str = None):
    """
    Returns the raw audit report (as generated by generate_report).
    Used by the dashboard to render the RBI Report tab.
    """
    logs = _fetch_logs(api_key, session_id)
    if not logs:
        return {"message": "No data yet for this api_key"}

    daos = _build_daos(logs)
    sid  = session_id or (logs[0].get("session_id") or "all")
    return generate_report(sid, daos)


@router.get("/report/cleaned")
async def get_cleaned_report(api_key: str, session_id: str = None):
    """
    Returns the cleaned + normalized report.
    decision_id auto-generated, reasoning filled, raw fields parsed,
    computed flags added, compliance percent/status added.
    """
    logs = _fetch_logs(api_key, session_id)
    if not logs:
        return {"message": "No data yet for this api_key"}

    daos = _build_daos(logs)
    sid  = session_id or (logs[0].get("session_id") or "all")
    raw  = generate_report(sid, daos)
    return clean_report(raw)


@router.get("/report/download")
async def download_report(api_key: str, session_id: str = None, cleaned: bool = True):
    """
    Returns the audit report as a downloadable JSON file attachment.

    Query params:
      - api_key:    required
      - session_id: optional filter
      - cleaned:    true (default) -> cleaned/normalized JSON
                    false          -> raw report as-is

    Filename: agentbridge-report-<session_id>-<date>-<cleaned|raw>.json
    """
    logs = _fetch_logs(api_key, session_id)
    if not logs:
        return JSONResponse(
            status_code=404,
            content={"message": "No data yet for this api_key"}
        )

    daos   = _build_daos(logs)
    sid    = session_id or (logs[0].get("session_id") or "all")
    raw    = generate_report(sid, daos)
    report = clean_report(raw) if cleaned else raw

    date_str = datetime.now(timezone.utc).strftime("%Y%m%d")
    label    = "cleaned" if cleaned else "raw"
    filename = f"agentbridge-report-{sid}-{date_str}-{label}.json"

    return JSONResponse(
        content=report,
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
            "Content-Type":        "application/json",
        }
    )


@router.get("/verify-chain")
async def verify_audit_chain(api_key: str):
    """
    Verify tamper-evidence of audit log chain.
    Returns {valid: bool, broken_at: decision_id|None, total_checked: int}
    """
    return verify_chain(api_key)
